name = "commerce-cloud-mcp-server"
main = "src/index.ts"
compatibility_date = "2025-06-08"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

# Durable Objects
[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "CommerceCloudMCP"

# Migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = ["CommerceCloudMCP"]

[vars]
SFCC_INSTANCE_URL = "https://zzra-078.dx.commercecloud.salesforce.com"
SFCC_DEFAULT_SITE_ID = "RefArch"
SFCC_VERSION = "v25_6"
SFCC_CLIENT_ID = "b865b2d5-761b-4240-b7e5-f686ec773eed"
# npx wrangler secret put SFCC_CLIENT_SECRET

# R2 bucket for MCP server resources
[[r2_buckets]]
binding = "MCP_RESOURCES"
bucket_name = "commerce-cloud-mcp-resources"

# Static assets configuration
[assets]
directory = "./public"
binding = "ASSETS"

# KV
[[kv_namespaces]]
binding = "OAUTH_KV"
id = "462343c8ae4e49efbf4844b5decc4180"
